// Define at the top of each page to set the metadata
export const metadata = {
	title: 'About US | Creative Studio',
	description: 'Generated by create next app',
}

export default function Page() {
	return (
		<div>
			<h1>About</h1>
			<p>This is the about page</p>
		</div>
	)
}
