import localFont from 'next/font/local'
import './globals.css'
import Navbar from './Components/Navigation'
import Footer from './Components/Footer'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata = {
	title: 'Masato Studios | Creative Studio',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
			  <Navbar />
        <main>
				{children}
        </main>
        <Footer />
			</body>
		</html>
	)
}
