import localFont from 'next/font/local'
import './globals.css'
import Footer from './Components/Footer'

// const geistMono = localFont({
// 	src: './fonts/GeistMonoVF.woff',
// 	variable: '--font-geist-mono',
// 	weight: '100 900',
// })

export const metadata = {
	title: 'Masato Studios | Creative Agency',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				{children}
				<Footer />
			</body>
		</html>
	)
}
